### ISSUE TITLE
cant bootstrap vulture4-HBSD12

### ISSUE THREAD

**Issue by ccmsi** [VultureProject/vulture-base#77]
Greetings.
Im using vulture4-HBSD12-amd64-disk001.vmdk of 2022-02-09 12:45. After booting i configured IP Address, time and hostname in admin.
Executing cluster_create.sh specifying new username/pwd i get the error message:
importerror shared object libldap_r-2.4.so.2 not found

**Comment by ccmsi** [comment]
root@vulture:/usr/home/vlt-adm # pkg search libldap
pkg: repository HardenedBSD contains packages for wrong OS version: FreeBSD:12:amd64
pkg: repository Vulture contains packages for wrong OS version: FreeBSD:12:amd64

**Comment by ccmsi** [comment]
while running update lite:

root@vulture:/home/vlt-adm/system # /home/vlt-adm/system/update_system_lite.sh 
....
[4/5] Upgrading vulture-gui from 1.3.8 to 1.12.1...
===> Removing django crontabs
ldap_int_sasl_init: SASL library version mismatch: expected 2.1.28, got 2.1.27
Traceback (most recent call last):
  File "/home/vlt-os/vulture_os/manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/home/vlt-os/env/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/home/vlt-os/env/lib/python3.8/site-packages/django/core/management/__init__.py", line 377, in execute
    django.setup()
  File "/home/vlt-os/env/lib/python3.8/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/vlt-os/env/lib/python3.8/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/home/vlt-os/env/lib/python3.8/site-packages/django/apps/config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/home/jails.apache/.zfs-source/home/vlt-os/vulture_os/workflow/models.py", line 34, in <module>
    from applications.backend.models import Backend
  File "/usr/home/jails.apache/.zfs-source/home/vlt-os/vulture_os/applications/backend/models.py", line 33, in <module>
    from services.haproxy.haproxy import hot_action_frontend, hot_action_backend, test_haproxy_conf, HAPROXY_OWNER, HAPROXY_PATH, HAPROXY_PERMS, TEST_CONF_PATH
  File "/usr/home/jails.apache/.zfs-source/home/vlt-os/vulture_os/services/haproxy/haproxy.py", line 31, in <module>
    from services.haproxy.models import HAProxySettings
  File "/usr/home/jails.apache/.zfs-source/home/vlt-os/vulture_os/services/haproxy/models.py", line 30, in <module>
    from system.cluster.models import Cluster
  File "/usr/home/jails.apache/.zfs-source/home/vlt-os/vulture_os/system/cluster/models.py", line 26, in <module>
    from system.config.models import Config
  File "/usr/home/jails.apache/.zfs-source/home/vlt-os/vulture_os/system/config/models.py", line 29, in <module>
    from authentication.ldap.models import LDAPRepository
  File "/usr/home/jails.apache/.zfs-source/home/vlt-os/vulture_os/authentication/ldap/models.py", line 36, in <module>
    from toolkit.auth.ldap_client import LDAPClient
  File "/usr/home/jails.apache/.zfs-source/home/vlt-os/vulture_os/toolkit/auth/ldap_client.py", line 32, in <module>
    import ldap
  File "/home/vlt-os/env/lib/python3.8/site-packages/ldap/__init__.py", line 39, in <module>
    LIBLDAP_API_INFO = _ldap.get_option(_ldap.OPT_API_INFO)
SystemError: error -2 from ldap_get_option

**Comment by ccmsi** [comment]
retrying for completeness after reboot:

root@vulture:/usr/home/vlt-adm # /home/vlt-adm/system/update_system_lite.sh 
[*] disabling root secadm rules
sysctlbyname: No such file or directory
could not flush rules. error code: -1
Could not disable secadm rules
[*] [mongodb] disabling secadm rules
sysctlbyname: No such file or directory
could not flush rules. error code: -1
Could not disable secadm rules
[*] [apache] disabling secadm rules
sysctlbyname: No such file or directory
could not flush rules. error code: -1
Could not disable secadm rules
[*] [portal] disabling secadm rules
sysctlbyname: No such file or directory
could not flush rules. error code: -1
Could not disable secadm rules
Updating HardenedBSD repository catalogue...
...

**Comment by ccmsi** [comment]
All in all if i didnt do things completely wrong, then vulture4-HBSD12-amd64-disk001.vmdk seems disfunctional. In that case i would rather have project management pull that version off the public face, as at least the experience i had is damaging to project reputation.
If i did sth wrong, i would ask for update / improvement of documentation, at least for installation it hsould not be too extensive a task. Also a dedicated reference thereto from main project page would be nice.
